spring:
  application:
    name: team-service
  zipkin:
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8083
eureka:
  instance:
    metadata-map:
      appDisplayName: Teams API
      swaggerPath: swagger-ui.html
      documentationPath: docs/index.html
